CREATE TABLE SUBBU(ID INT ,FILED INT,MARKS INT);
TABLE SUBBU;
INSERT INTO SUBBU VALUES(1,1,1),(NULL,NULL,NULL),(1,NULL,NULL);
SELECT COUNT(*) FROM SUBBU;  -- IT WILL INCLUDE NULL AND DUPLICATES ALSO
SELECT COUNT(ID) FROM SUBBU; -- IT WILL DOESNOT INCLUDE NULL,AND ALLOW DUPLICATES
SELECT COUNT(DISTINCT ID) FROM SUBBU; -- IT WILL DOESN'T ALLOW NULL AND DUPLICATES